stages:
  - lint
  - format
  - type_check
  - test
  - coverage

variables:
  UV_SYSTEM_PYTHON: "1"

default:
  image: python:3.12

before_script:
  - python --version
  - pip install uv
  - uv sync

ruff:
  stage: lint
  script:
    - uv run ruff check .

ruff-format:
  stage: format
  script:
    - uv run ruff format --check .

mypy:
  stage: type_check
  script:
    - uv run mypy src

test:
  stage: test
  script:
    - uv run pytest

coverage:
  stage: coverage
  script:
    - uv run pytest --cov=src --cov-report=term